### ISSUE TITLE
Database url not read from .env file.

### ISSUE THREAD

**Issue by shibacomputer** [calendso/docker#11]
Following the steps to the letter in this, it appears that the postgres url supplied in the `.env` file is not passed to the build process.

This results in errors both in the `docker-compose logs` output, and also error messages visible via Prisma studio.
```
calendso_1  | Prisma schema loaded from prisma/schema.prisma
calendso_1  | Error: Get config: Schema Parsing P1012
calendso_1  |
calendso_1  | error: Error validating datasource `db`: the URL must start with the protocol `postgresql://` or `postgres://`.
calendso_1  |   -->  schema.prisma:6
calendso_1  |    |
calendso_1  |  5 |   provider = "postgresql"
calendso_1  |  6 |   url      = env("DATABASE_URL")
calendso_1  |    |
calendso_1  |
calendso_1  | Validation Error Count: 1
calendso_1  |
```
![image](https://user-images.githubusercontent.com/737950/130816104-55a2836e-182b-458f-80bf-e83f07e2271e.png)

For what it's worth, manually updating `calendso/prisma/schema.prisma` with the desired URL allows Calendso to successfully deploy, but is not an ideal solution.

**Comment by krumware** [comment]
The single/double quotes must be removed from the .env file in order for this to work properly. Docker doesn't respect them in the env files. This also affects the GOOGLE_API_CREDENTIALS, the json object must not be wrapped in quotes or else the variable is interpreted as `'{}'`

With single quotes:
```
warn  - Disabled 'Google Calendar' integration. Reason: Invalid value for GOOGLE_API_CREDENTIALS environment variable. When set, this value needs to contain valid JSON like {"web":{"client_id":"<clid>","client_secret":"<secret>","redirect_uris":["<yourhost>/api/integrations/googlecalendar/callback>"]}. You can download this JSON from your OAuth Client @ https://console.cloud.google.com/apis/credentials.
```

Tested on Docker Desktop 4.1 in WSL
https://dev.to/tvanantwerp/don-t-quote-environment-variables-in-docker-268h

**Comment by kelvinalfaro** [comment]
I removed the single and double quotes didn't help. 
Any other way to resolved this?

**Comment by agapejon** [comment]
same issue, removed the quotes but still getting the same error

**Comment by krumware** [comment]
@kelvinalfaro @agapejon does anything change if you use `yarn dev` instead of `yarn start`?

also, I did some significant rework of the dockerfile, since I had other issues with the use of yarn build that I haven't pushed through yet. `yarn build` is likely generating static files at docker build time, which wont include the .env variables used by docker-compose. `yarn dev` should support runtime compile with env vars.

```
FROM node:14-alpine as deps

RUN apk add --no-cache libc6-compat
RUN mkdir app
COPY calendso/package.json calendso/yarn.lock /app/
COPY calendso/prisma /app/prisma
WORKDIR /app
RUN ls
RUN yarn install

FROM node:14-alpine as builder
COPY calendso /app
COPY --from=deps /app/node_modules /app/node_modules
WORKDIR /app
# RUN yarn install

FROM node:14-alpine as runner
ENV NODE_ENV production

# copy all files
COPY --from=builder /app /app
COPY .env /app/.env
# COPY --from=builder /app/next.config.js ./
# COPY --from=builder /app/public ./public
# COPY --from=builder /app/.next ./.next
# COPY --from=builder /app/node_modules ./node_modules
# COPY --from=builder /app/package.json ./package.json
# COPY --from=builder /app/prisma ./prisma
COPY  scripts /app/scripts
WORKDIR /app
EXPOSE 3000
CMD ["/app/scripts/start.sh"]
```

**Comment by kelvinalfaro** [comment]
Thanks. This worked well. Though I gave up on it for now. Once it deployed, i was unable to set up the database. Maybe will try again soon. Your response was really appreciated however.

**Comment by krumware** [comment]
That may be a combination with my other issue posted. I'll get a WIP branch up to try early this week

**Comment by vanceism7** [comment]
@krumware Trying the new Dockerfile got me further in the process, but I get this error when running 
`sudo docker-compose up --build`

error:
> Error: Could not find a production build in the '/app/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id

Adding `yarn build` into the `start.sh` script got the app to run successfully, but not sure if that's really the proper thing to do here

**Comment by krumware** [comment]
Ah, must have left that in there while trying things. I've been working on this locally today, I'll see if I can clean it up

**Comment by krumware** [comment]
Can you also by chance try `yarn dev` instead of yarn build in the start file?

**Comment by vanceism7** [comment]
Ah, yea, using the new dockerfile you provided + changing `yarn start` to `yarn dev` in `scripts/start.sh` got it working. Thanks!

**Comment by vanceism7** [comment]
Ah wait, nvm. If I replace `yarn start` with `yarn dev` - docker-compose successfully starts the app, but then the app doesn't actually work. The website spews the following error:
> TypeError: (0 , react_jsx_dev_runtime__WEBPACK_IMPORTED_MODULE_0__.jsxDEV) is not a function

Naively searching for that error online, I found this
https://github.com/vercel/next.js/issues/26983

Keeping `yarn start` and adding `yarn build` the line before seems to avoid this error

**Comment by vanceism7** [comment]
Just tried it - its working!

**Comment by drwb** [comment]
I've been following along and this evening went through these steps (Replaced Dockerfile, added NODE_ENV=development, changed `yarn start` to `yarn dev`) and we get to the following, and it then hangs:
<img width="1358" alt="Screenshot 2021-10-05 at 23 28 00" src="https://user-images.githubusercontent.com/16479230/136111525-d7032f76-7fab-4709-ab0b-099dfec50a6b.png">

although it seems hitting the container on :3000 triggers the JIT compilation and throws this error:
<img width="1363" alt="Screenshot 2021-10-05 at 23 28 13" src="https://user-images.githubusercontent.com/16479230/136111566-dc59629b-82af-4927-ae61-b7b3068798fe.png">

It feels like we're nearly there.

**Comment by krumware** [comment]
I've been seeing that as well.  This won't be a final solution anyways, however, because we won't want to use yarn dev in production. I'll typically move `yarn dev` to `command` in the docker-compose file, and how how to mount a local volume for using docker-compose for development. Still working on a proper prod build and have notes on some of the other threads.

@vanceism7 I have that JWT_SECRET included in mine after copying some extras from calendso/calendso while debugging. good pointer!

**Comment by killjoy2013** [comment]
> The single/double quotes must be removed from the .env file in order for this to work properly. Docker doesn't respect them in the env files.
> 
> working example: (I added POSTGRES_HOST for better capability with start.sh)
> 
> ```
> DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}
> ```
> 
> This also affects the GOOGLE_API_CREDENTIALS, the json object must not be wrapped in quotes or else the variable is interpreted as `'{}'`
> 
> With single quotes:
> 
> ```
> warn  - Disabled 'Google Calendar' integration. Reason: Invalid value for GOOGLE_API_CREDENTIALS environment variable. When set, this value needs to contain valid JSON like {"web":{"client_id":"<clid>","client_secret":"<secret>","redirect_uris":["<yourhost>/api/integrations/googlecalendar/callback>"]}. You can download this JSON from your OAuth Client @ https://console.cloud.google.com/apis/credentials.
> ```
> 
> Tested on Docker Desktop 4.1 in WSL https://dev.to/tvanantwerp/don-t-quote-environment-variables-in-docker-268h

Thank you :-)
