### ISSUE TITLE
docker-compose up --build fails

### ISSUE THREAD

**Issue by deeztek** [calendso/docker#12]
Trying to build the image with:

`docker-compose up --build`

and I get the following error:

 ```
COPY calendso/package.json calendso/yarn.lock ./
ERROR: Service 'calendso' failed to build: COPY failed: file not found in build context or excluded by .dockerignore: stat calendso/package.json: file does not exist
```

**Comment by emrysal** [comment]
Did you clone this repo with the `--recursive` flag ensure the installation of the submodule?

`git clone git@github.com:calendso/calendso-docker.git --recursive`

**Comment by deeztek** [comment]
Well that particular command causes another error:

```
git clone git@github.com:calendso/calendso-docker.git --recursive
Cloning into 'calendso-docker'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by deeztek** [comment]
This command actually worked:

`git clone https://github.com/calendso/docker.git --recursive`

**Comment by deeztek** [comment]
New error trying to create a user in prisma:

Message: Error in Prisma Client request: 

error: Error validating datasource `db`: the URL must start with the protocol `postgresql://` or `postgres://`.
  -->  schema.prisma:6
   | 
 5 |   provider = "postgresql"
 6 |   url      = env("DATABASE_URL")
   | 

Validation Error Count: 1
  
Query:
prisma.user.findMany({
  take: 100,
  skip: 0,
  select: {
    id: true,
    username: true,
    name: true,
    email: true,
    emailVerified: true,
    password: true,
    bio: true,
    avatar: true,
    timeZone: true,
    weekStart: true,
    startTime: true,
    endTime: true,
    bufferTime: true,
    hideBranding: true,
    theme: true,
    createdDate: true,
    eventTypes: true,
    credentials: true,
    teams: true,
    bookings: true,
    availability: true,
    selectedCalendars: true,
  }
})
  

Is the docker image completely broken or am I missing something?

**Comment by emrysal** [comment]
Strange, same thing reported here: https://github.com/calendso/docker/issues/11

I don't have the time to have a look at it myself as I'm completing the team events feature- after I've completed that I'll take an look what's going on, but it definitely used to work.

**Comment by deeztek** [comment]
I'm able to get it working by creating a copy of prisma.schema with the following hardcoded info:

```
datasource db {
  provider = "postgresql"
  url      = "postgresql://user:password@calendso_db:5432/calendsodb"
}
```

and adding as a volume to the calendso container as follows:

```
    volumes:
      - ./schema.prisma:/app/prisma/schema.prisma
```

seems to work as suggested at #11 

This is of course not ideal. Is the prisma integration only for the purposes of creating the first account? If so, wouldn't be simpler to create a default user/password and after logging in simply change the password?

Thanks
