### ISSUE TITLE
Can't pull image from docker hub

### ISSUE THREAD

**Issue by dotesfera** [calendso/docker#18]
Doing docker pull calendso/calendso gives this error:

![image](https://user-images.githubusercontent.com/30806279/134331018-d9d1a0bb-f7cd-44f3-a548-64688cb253b9.png)

**Comment by dotesfera** [comment]
I think this is caused because there's no tag information on docker hub

**Comment by dotesfera** [comment]
Please add a tag info on docker hub...

**Comment by krumware** [comment]
progress in #2
