### ISSUE TITLE
Docker Hub

### ISSUE THREAD

**Issue by dotesfera** [calendso/docker#2]
Will this be on Docker Hub?

**Comment by emrysal** [comment]
Yes, currently looking into that; Given all goes well curating the image and a completed Docker Hub on-boarding the image will be added to the platform.

**Comment by Robert-Ernst** [comment]
So when will this happen?

**Comment by PeerRich** [comment]
https://hub.docker.com/r/calendso/calendso

**Comment by dotesfera** [comment]
This should have a tag on docker hub. Can even find the image using Portainer.

**Comment by PeerRich** [comment]
i am not quite sure if i understand the problem. this docker repo is community maintained and an official image is on docker hub. am i missing something?

would love to help!

**Comment by dotesfera** [comment]
I have Synology Docker service and trying to download the image gives me this error:
![image](https://user-images.githubusercontent.com/30806279/133100580-dd134b6b-da43-4c12-b4ad-a4411c065594.png)

**Comment by dotesfera** [comment]
Do you understood what I meant? There should be a tag:latest maybe

**Comment by krumware** [comment]
@PeerRich, to echo @dotesfera, this image is not possible to pull from dockerhub currently. It needs to be re-pushed, or perhaps re-tagged with latest and pushed, `docker build . -t calendso/calendso:latest`

```
> docker pull calendso/calendso
Using default tag: latest
Error response from daemon: manifest for calendso/calendso:latest not found: manifest unknown: manifest unknown
```

```
> docker pull -a calendso/calendso
Error response from daemon: repository calendso/calendso not found: name unknown: repository name not known to registry
```

**Comment by PeerRich** [comment]
we'll take care of it!

**Comment by dotesfera** [comment]
Hi, just passing by if there are any news?
