### ISSUE TITLE
Unable to login 

### ISSUE THREAD

**Issue by LeducH** [calendso/docker#4]
I want to test the app inside the docker container 

I followed the steps from the README

I used https://bcrypt-generator.com/ to encrypt my password. 

but I get 

> Incorrect password
> An error occurred when logging you in. Head back to the login screen and try again.

**Comment by emrysal** [comment]
Depending on the way you enter the password, always triple check the database entry for your b crypt hash. Maybe take the DB value and compare it with a string in bcrypt-generator, and eliminate the chance for typos.

**Comment by jurgenhaas** [comment]
Had the same problem. Reason was that when clicking on the "Copy" button on https://bcrypt-generator.com/ and paste that value into the database field, you end up with a trailing space. Remove that space and you're goog to go.

**Comment by emrysal** [comment]
@jurgenhaas I knew it was going to be something like that.. that's good to know! @LeducH see above replies - closing this.
