### ISSUE TITLE
How can I add integrations

### ISSUE THREAD

**Issue by jurgenhaas** [calendso/docker#6]
I'm a bit confused about the pricing model of Calendso. It says that the free (self-hosted) version does NOT come with the option "Ready-to-connect integrations". That gets me to assume that we have to install integrations ourselves. That's fine, I just wonder where I could find any. Or am I not supposed to have calenders integrated at all?

**Comment by PeerRich** [comment]
> I'm a bit confused about the pricing model of Calendso. It says that the free (self-hosted) version does NOT come with the option "Ready-to-connect integrations". That gets me to assume that we have to install integrations ourselves. That's fine, I just wonder where I could find any. Or am I not supposed to have calenders integrated at all?

hey there. Correct, there is a technical limitation of every open source project that you need to create API keys of each integration that you're looking to use.

**Comment by jurgenhaas** [comment]
OK, does this relate to the `.env` file with API keys for Google calendar and Outlook? Is there a way to integrate calendars that are not from those 2 problematic providers in terms of privacy? I mean WebCAL for example? If not, is there a way to start working on this as part of the open source project?

**Comment by PeerRich** [comment]
> OK, does this relate to the `.env` file with API keys for Google calendar and Outlook? Is there a way to integrate calendars that are not from those 2 problematic providers in terms of privacy? I mean WebCAL for example? If not, is there a way to start working on this as part of the open source project?

yes it relates to any integration (gcal, zoom, outlook, ...)

CalDav is launching this week afaik

But we'd love to have your contribution too!

**Comment by jurgenhaas** [comment]
Great, I'll have a look what's coming and will provide feedback, etc.

**Comment by PeerRich** [comment]
CalDav has been out for a few weeks now

**Comment by jurgenhaas** [comment]
Thanks, but it's not available for self-hosted solutions - which is the whole purpose of this Docker repo, I guess.
