### ISSUE TITLE
User create error

### ISSUE THREAD

**Issue by SuperDarius-git** [calendso/docker#68]
Hi

I am having a problem when I create my first user. Please help.

**The error is:** 
![image](https://user-images.githubusercontent.com/29814230/148560091-66b68c38-4f6c-4576-964d-50dea7aa94d5.png)

**and the details are:**
```

Type: PrismaClientValidationError
Message: 
Invalid `prisma.user.create()` invocation:

{
  data: {
    id: 1,
    ~~
    username: 'superdarius',
    name: 'Darius Oosthuizen',
    email: 'darius@super.org.za',
    emailVerified: null,
    password: '**********',
    bio: null,
    avatar: null,
    timeZone: 'Africa/Johannesburg',
    weekStart: 'Sunday',
    startTime: 0,
    endTime: 1440,
    bufferTime: 0,
    hideBranding: false,
    theme: null,
    createdDate: '2021-12-31T22:00:00.000Z',
    eventTypes: {},
    credentials: {},
    teams: {},
    bookings: {},
    availability: {},
    selectedCalendars: {},
    completedOnboarding: false,
    locale: null,
    twoFactorSecret: null,
    twoFactorEnabled: false,
    plan: 'PRO',
    Schedule: {},
    webhooks: {},
    brandColor: '#292929',
    metadata: null
              ~~~~
  },
  select: {
    id: true,
    username: true,
    name: true,
    email: true,
    emailVerified: true,
    password: true,
    bio: true,
    avatar: true,
    timeZone: true,
    weekStart: true,
    startTime: true,
    endTime: true,
    bufferTime: true,
    hideBranding: true,
    theme: true,
    createdDate: true,
    eventTypes: true,
    credentials: true,
    teams: true,
    bookings: true,
    availability: true,
    selectedCalendars: true,
    completedOnboarding: true,
    locale: true,
    twoFactorSecret: true,
    twoFactorEnabled: true,
    plan: true,
    Schedule: true,
    webhooks: true,
    brandColor: true,
    destinationCalendar: true,
    metadata: true
  }
}

Unknown arg `id` in data.id for type UserCreateInput. Did you mean `bio`? Available args:
type UserCreateInput {
  username?: String | Null
  name?: String | Null
  email: String
  emailVerified?: DateTime | Null
  password?: String | Null
  bio?: String | Null
  avatar?: String | Null
  timeZone?: String
  weekStart?: String
  startTime?: Int
  endTime?: Int
  bufferTime?: Int
  hideBranding?: Boolean
  theme?: String | Null
  createdDate?: DateTime
  completedOnboarding?: Boolean
  locale?: String | Null
  twoFactorSecret?: String | Null
  twoFactorEnabled?: Boolean
  plan?: UserPlan
  brandColor?: String
  metadata?: NullableJsonNullValueInput | Json
  eventTypes?: EventTypeCreateNestedManyWithoutUsersInput
  credentials?: CredentialCreateNestedManyWithoutUserInput
  teams?: MembershipCreateNestedManyWithoutUserInput
  bookings?: BookingCreateNestedManyWithoutUserInput
  availability?: AvailabilityCreateNestedManyWithoutUserInput
  selectedCalendars?: SelectedCalendarCreateNestedManyWithoutUserInput
  Schedule?: ScheduleCreateNestedManyWithoutUserInput
  webhooks?: WebhookCreateNestedManyWithoutUserInput
  destinationCalendar?: DestinationCalendarCreateNestedOneWithoutUserInput
}
Argument metadata for data.metadata must not be null. Please use undefined instead.



Code: undefined

Query:
prisma.user.create(
{
  data: {
    id: 1,
    username: "superdarius",
    name: "Darius Oosthuizen",
    email: "darius@super.org.za",
    emailVerified: null,
    password: "***********",
    bio: null,
    avatar: null,
    timeZone: "Africa/Johannesburg",
    weekStart: "Sunday",
    startTime: 0,
    endTime: 1440,
    bufferTime: 0,
    hideBranding: false,
    theme: null,
    createdDate: "2021-12-31T22:00:00.000Z",
    eventTypes: {

    },
    credentials: {

    },
    teams: {

    },
    bookings: {

    },
    availability: {

    },
    selectedCalendars: {

    },
    completedOnboarding: false,
    locale: null,
    twoFactorSecret: null,
    twoFactorEnabled: false,
    plan: "PRO",
    Schedule: {

    },
    webhooks: {

    },
    brandColor: "#292929",
    metadata: null,
  },
  select: {
    id: true,
    username: true,
    name: true,
    email: true,
    emailVerified: true,
    password: true,
    bio: true,
    avatar: true,
    timeZone: true,
    weekStart: true,
    startTime: true,
    endTime: true,
    bufferTime: true,
    hideBranding: true,
    theme: true,
    createdDate: true,
    eventTypes: true,
    credentials: true,
    teams: true,
    bookings: true,
    availability: true,
    selectedCalendars: true,
    completedOnboarding: true,
    locale: true,
    twoFactorSecret: true,
    twoFactorEnabled: true,
    plan: true,
    Schedule: true,
    webhooks: true,
    brandColor: true,
    destinationCalendar: true,
    metadata: true,
  },
}
)
```

**Comment by MR-Os1** [comment]
Hello
I resolved this issue by adding the {} of json instead of null field in metadata column.
the pull request is also in progress.
Thank you for noticing the issue.

**Comment by krumware** [comment]
Hi folks, I'm hoping to clarify this issue.
Do you know which field caused the issue for you? 
![image](https://user-images.githubusercontent.com/17303782/148846640-03c53663-b7df-46a6-bd94-161d362eacbe.png)

**Comment by SuperDarius-git** [comment]
@krumware I'm not sure where the error comes from. I think it is from the "metadata" field, but when I added {} as @MR-Os1 suggested, I get another error as below (slightly different than the previous error):

![image](https://user-images.githubusercontent.com/29814230/148919735-bd9bcb02-f6c5-4634-949f-1e8972aeb390.png)

and the following details:

`Type: PrismaClientValidationError
Message: 
Invalid `prisma.user.create()` invocation:

{
  data: {
    id: 1,
    ~~
    username: 'superdarius',
    name: 'Darius Oosthuizen',
    email: 'darius@super.org.za',
    emailVerified: null,
    password: 'dummy',
    bio: null,
    avatar: null,
    timeZone: 'Africa/Johannesburg',
    weekStart: 'Sunday',
    startTime: 0,
    endTime: 1440,
    bufferTime: 0,
    hideBranding: false,
    theme: null,
    createdDate: '2021-12-31T22:00:00.000Z',
    eventTypes: {},
    credentials: {},
    teams: {},
    bookings: {},
    availability: {},
    selectedCalendars: {},
    completedOnboarding: false,
    locale: null,
    twoFactorSecret: null,
    twoFactorEnabled: false,
    plan: 'PRO',
    Schedule: {},
    webhooks: {},
    brandColor: '#292929',
    metadata: {}
  },
  select: {
    id: true,
    username: true,
    name: true,
    email: true,
    emailVerified: true,
    password: true,
    bio: true,
    avatar: true,
    timeZone: true,
    weekStart: true,
    startTime: true,
    endTime: true,
    bufferTime: true,
    hideBranding: true,
    theme: true,
    createdDate: true,
    eventTypes: true,
    credentials: true,
    teams: true,
    bookings: true,
    availability: true,
    selectedCalendars: true,
    completedOnboarding: true,
    locale: true,
    twoFactorSecret: true,
    twoFactorEnabled: true,
    plan: true,
    Schedule: true,
    webhooks: true,
    brandColor: true,
    destinationCalendar: true,
    metadata: true
  }
}

Unknown arg `id` in data.id for type UserCreateInput. Did you mean `bio`? Available args:
type UserCreateInput {
  username?: String | Null
  name?: String | Null
  email: String
  emailVerified?: DateTime | Null
  password?: String | Null
  bio?: String | Null
  avatar?: String | Null
  timeZone?: String
  weekStart?: String
  startTime?: Int
  endTime?: Int
  bufferTime?: Int
  hideBranding?: Boolean
  theme?: String | Null
  createdDate?: DateTime
  completedOnboarding?: Boolean
  locale?: String | Null
  twoFactorSecret?: String | Null
  twoFactorEnabled?: Boolean
  plan?: UserPlan
  brandColor?: String
  metadata?: NullableJsonNullValueInput | Json
  eventTypes?: EventTypeCreateNestedManyWithoutUsersInput
  credentials?: CredentialCreateNestedManyWithoutUserInput
  teams?: MembershipCreateNestedManyWithoutUserInput
  bookings?: BookingCreateNestedManyWithoutUserInput
  availability?: AvailabilityCreateNestedManyWithoutUserInput
  selectedCalendars?: SelectedCalendarCreateNestedManyWithoutUserInput
  Schedule?: ScheduleCreateNestedManyWithoutUserInput
  webhooks?: WebhookCreateNestedManyWithoutUserInput
  destinationCalendar?: DestinationCalendarCreateNestedOneWithoutUserInput
}



Code: undefined

Query:
prisma.user.create(
{
  data: {
    id: 1,
    username: "superdarius",
    name: "Darius Oosthuizen",
    email: "darius@super.org.za",
    emailVerified: null,
    password: "dummy",
    bio: null,
    avatar: null,
    timeZone: "Africa/Johannesburg",
    weekStart: "Sunday",
    startTime: 0,
    endTime: 1440,
    bufferTime: 0,
    hideBranding: false,
    theme: null,
    createdDate: "2021-12-31T22:00:00.000Z",
    eventTypes: {

    },
    credentials: {

    },
    teams: {

    },
    bookings: {

    },
    availability: {

    },
    selectedCalendars: {

    },
    completedOnboarding: false,
    locale: null,
    twoFactorSecret: null,
    twoFactorEnabled: false,
    plan: "PRO",
    Schedule: {

    },
    webhooks: {

    },
    brandColor: "#292929",
    metadata: {

    },
  },
  select: {
    id: true,
    username: true,
    name: true,
    email: true,
    emailVerified: true,
    password: true,
    bio: true,
    avatar: true,
    timeZone: true,
    weekStart: true,
    startTime: true,
    endTime: true,
    bufferTime: true,
    hideBranding: true,
    theme: true,
    createdDate: true,
    eventTypes: true,
    credentials: true,
    teams: true,
    bookings: true,
    availability: true,
    selectedCalendars: true,
    completedOnboarding: true,
    locale: true,
    twoFactorSecret: true,
    twoFactorEnabled: true,
    plan: true,
    Schedule: true,
    webhooks: true,
    brandColor: true,
    destinationCalendar: true,
    metadata: true,
  },
}
)`

**Comment by MR-Os1** [comment]
> Hi folks, I'm hoping to clarify this issue. Do you know which field caused the issue for you? ![image](https://user-images.githubusercontent.com/17303782/148846640-03c53663-b7df-46a6-bd94-161d362eacbe.png)

![image](https://user-images.githubusercontent.com/21277208/149332757-f0c33bca-7840-43f4-a535-6d3f941eef53.png)

the last field

**Comment by MR-Os1** [comment]
> @krumware I'm not sure where the error comes from. I think it is from the "metadata" field, but when I added {} as @MR-Os1 suggested, I get another error as below (slightly different than the previous error):
> 
> ![image](https://user-images.githubusercontent.com/29814230/148919735-bd9bcb02-f6c5-4634-949f-1e8972aeb390.png)
> 
> and the following details:
> 
> ```
> Type: PrismaClientValidationError
> Message: 
> Invalid `prisma.user.create()` invocation:
> 
> {
>   data: {
>     id: 1,
>     ~~
>     username: 'superdarius',
>     name: 'Darius Oosthuizen',
>     email: 'darius@super.org.za',
>     emailVerified: null,
>     password: 'dummy',
>     bio: null,
>     avatar: null,
>     timeZone: 'Africa/Johannesburg',
>     weekStart: 'Sunday',
>     startTime: 0,
>     endTime: 1440,
>     bufferTime: 0,
>     hideBranding: false,
>     theme: null,
>     createdDate: '2021-12-31T22:00:00.000Z',
>     eventTypes: {},
>     credentials: {},
>     teams: {},
>     bookings: {},
>     availability: {},
>     selectedCalendars: {},
>     completedOnboarding: false,
>     locale: null,
>     twoFactorSecret: null,
>     twoFactorEnabled: false,
>     plan: 'PRO',
>     Schedule: {},
>     webhooks: {},
>     brandColor: '#292929',
>     metadata: {}
>   },
>   select: {
>     id: true,
>     username: true,
>     name: true,
>     email: true,
>     emailVerified: true,
>     password: true,
>     bio: true,
>     avatar: true,
>     timeZone: true,
>     weekStart: true,
>     startTime: true,
>     endTime: true,
>     bufferTime: true,
>     hideBranding: true,
>     theme: true,
>     createdDate: true,
>     eventTypes: true,
>     credentials: true,
>     teams: true,
>     bookings: true,
>     availability: true,
>     selectedCalendars: true,
>     completedOnboarding: true,
>     locale: true,
>     twoFactorSecret: true,
>     twoFactorEnabled: true,
>     plan: true,
>     Schedule: true,
>     webhooks: true,
>     brandColor: true,
>     destinationCalendar: true,
>     metadata: true
>   }
> }
> 
> Unknown arg `id` in data.id for type UserCreateInput. Did you mean `bio`? Available args:
> type UserCreateInput {
>   username?: String | Null
>   name?: String | Null
>   email: String
>   emailVerified?: DateTime | Null
>   password?: String | Null
>   bio?: String | Null
>   avatar?: String | Null
>   timeZone?: String
>   weekStart?: String
>   startTime?: Int
>   endTime?: Int
>   bufferTime?: Int
>   hideBranding?: Boolean
>   theme?: String | Null
>   createdDate?: DateTime
>   completedOnboarding?: Boolean
>   locale?: String | Null
>   twoFactorSecret?: String | Null
>   twoFactorEnabled?: Boolean
>   plan?: UserPlan
>   brandColor?: String
>   metadata?: NullableJsonNullValueInput | Json
>   eventTypes?: EventTypeCreateNestedManyWithoutUsersInput
>   credentials?: CredentialCreateNestedManyWithoutUserInput
>   teams?: MembershipCreateNestedManyWithoutUserInput
>   bookings?: BookingCreateNestedManyWithoutUserInput
>   availability?: AvailabilityCreateNestedManyWithoutUserInput
>   selectedCalendars?: SelectedCalendarCreateNestedManyWithoutUserInput
>   Schedule?: ScheduleCreateNestedManyWithoutUserInput
>   webhooks?: WebhookCreateNestedManyWithoutUserInput
>   destinationCalendar?: DestinationCalendarCreateNestedOneWithoutUserInput
> }
> 
> 
> 
> Code: undefined
> 
> Query:
> prisma.user.create(
> {
>   data: {
>     id: 1,
>     username: "superdarius",
>     name: "Darius Oosthuizen",
>     email: "darius@super.org.za",
>     emailVerified: null,
>     password: "dummy",
>     bio: null,
>     avatar: null,
>     timeZone: "Africa/Johannesburg",
>     weekStart: "Sunday",
>     startTime: 0,
>     endTime: 1440,
>     bufferTime: 0,
>     hideBranding: false,
>     theme: null,
>     createdDate: "2021-12-31T22:00:00.000Z",
>     eventTypes: {
> 
>     },
>     credentials: {
> 
>     },
>     teams: {
> 
>     },
>     bookings: {
> 
>     },
>     availability: {
> 
>     },
>     selectedCalendars: {
> 
>     },
>     completedOnboarding: false,
>     locale: null,
>     twoFactorSecret: null,
>     twoFactorEnabled: false,
>     plan: "PRO",
>     Schedule: {
> 
>     },
>     webhooks: {
> 
>     },
>     brandColor: "#292929",
>     metadata: {
> 
>     },
>   },
>   select: {
>     id: true,
>     username: true,
>     name: true,
>     email: true,
>     emailVerified: true,
>     password: true,
>     bio: true,
>     avatar: true,
>     timeZone: true,
>     weekStart: true,
>     startTime: true,
>     endTime: true,
>     bufferTime: true,
>     hideBranding: true,
>     theme: true,
>     createdDate: true,
>     eventTypes: true,
>     credentials: true,
>     teams: true,
>     bookings: true,
>     availability: true,
>     selectedCalendars: true,
>     completedOnboarding: true,
>     locale: true,
>     twoFactorSecret: true,
>     twoFactorEnabled: true,
>     plan: true,
>     Schedule: true,
>     webhooks: true,
>     brandColor: true,
>     destinationCalendar: true,
>     metadata: true,
>   },
> }
> )`
> ```
> ```

I think you have tried to fill the id field  in table which is a auto increment field in the table.
if you left it with default content it will work.

**Comment by SuperDarius-git** [comment]
Thank you to all! That worked!!!!

**Comment by SuperDarius-git** [comment]
I do have 2 more questions for you. And please forgive me if it is stupid questions.
1. I am trying to accept the license, but I'm not sure how to do it. What I did is in Portainer I duplicated/edited the container and changed the .env variables to 'agree', but it does not seem to have worked.
2. Secondly, where do I change the URL from localhost:3000 to my public URL?

Thank you in advance!
Darius

**Comment by MR-Os1** [comment]
> I do have 2 more questions for you. And please forgive me if it is stupid questions.
> 
> 1. I am trying to accept the license, but I'm not sure how to do it. What I did is in Portainer I duplicated/edited the container and changed the .env variables to 'agree', but it does not seem to have worked.
> 2. Secondly, where do I change the URL from localhost:3000 to my public URL?
> 
> Thank you in advance! Darius

For your first  question I think  you should get a license for that box to go away  and for the second one you have to change BASE_URL and NEXT_PUBLIC_APP_URL in .env to change the public URL.

**Comment by SuperDarius-git** [comment]
Thanks Everyone!
