### ISSUE TITLE
Need some more explanations about some .env variables

### ISSUE THREAD

**Issue by ovizii** [calendso/docker#69]
I just found out about cal.com and the self-hosted Docker based version a few days ago and would like to give it a spin on my NAS for my own usage. I'd appreciate any comments on my probably silly questions.

I'm talking about this file: https://github.com/calendso/docker/blob/main/.env.example 

To which line does line 1 refer? do I set line 8 or 9 to 'agree' and what about the other one then? My guess is on line 8 but not sure about line 9 then.

![image](https://user-images.githubusercontent.com/837902/148849713-fb6e077b-a526-47da-8c8c-67fc3a43c87c.png)

I'm going to run this on my NAS and not on my local pc so localhost won't work for me. Can i replace both occurrences of localhost with my NAS's internal IP? 

What if I access it via a reverse proxy on i.e. cal.mydomain.tld? Do I need to pass over my public URL in line 12 and keep line 11 with my NAS's internal IP or does this then need the IP of its Docker container instead?

![image](https://user-images.githubusercontent.com/837902/148849998-9e5c9fe0-be25-430c-8071-9ebe3a2192f3.png)

What about the API keys, IDs and secrets? Any hints on what I need each for and possibly where to get them from?

![image](https://user-images.githubusercontent.com/837902/148850132-de28cea0-1162-45f4-b8ea-0d9dac2d0031.png)

And finally, just out of curiosity, why do some of your variables start with 'NEXT_' ? Just wondering what the background of that choice is :-)

**Comment by krumware** [comment]
1: is referring to 8 and 9
8 and 9, set both to `agree` if you agree with the license terms. (I am not yet certain that the variables are not used interchangeably)
11: probably leave the BASE_URL as `http://localhost:3000`, there is a fetch that happens internally, and will fail if your infrastructure does not update the container with service discovery of itself
12: this is the public facing url. It is used in some areas of the UI where a relative path may not be used to reliably generate URLs. (like the preview and share links for event types)
19+: instructions are in the calendso/calendso documentation and are not docker-specific. I believe those are all used server-side and do not have the same static build challenges mentioned in the other thread.

**Comment by krumware** [comment]
The `NEXT_` prefix is for variables used by the next.js framework that cal.com uses under the hood.

**Comment by ovizii** [comment]
thank you so much for taking time to help. That should get me going.
