### ISSUE TITLE
Docker OCI runtime exec failed

### ISSUE THREAD

**Issue by icolab** [calendso/docker#7]
Hello, 
I'm trying to install on my archlinux server Calendso with docker. The build was succesful however when I launched the second command line, I got the following error:

`docker-compose exec calendso -- npx prisma studio
OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "--": executable file not found in $PATH: unknown`

Have you ever seen this error? 
Sincerely

**Comment by bagheera2382** [comment]
Hello,
Same problem for me. Solved by removing `--`
So : 
`docker-compose exec calendso  npx prisma studio`

**Comment by icolab** [comment]
Thanks for the solution, it works for me!
