### ISSUE TITLE
Docker image failing to build after submodule update

### ISSUE THREAD

**Issue by krumware** [calendso/docker#72]
Docker image failed to build early this morning after the automatic submodule update. Needs to be investigated.

**Comment by searsaw** [comment]
I was able to build the Docker image after [the most recent auto-update](584a77082c0c8fc46cf4c4a6a7902847d4aa4b8a).

**Comment by krumware** [comment]
Yup, I was able to trigger the submodule update and build about an hour ago. Thanks y'all!
