### ISSUE TITLE
Site reloads constantly after choosing a date

### ISSUE THREAD

**Issue by ipozow** [calendso/docker#8]
So after a successful Calendso installation with Docker, everything is working good but the site is refreshing every time and asks to send a message. I don't know if I am doing something wrong or if it's a bug. I recorded a video that shows everything: 

https://user-images.githubusercontent.com/10505413/129274627-b0faabdc-4123-4adb-9fc4-f88a700b9c0e.mov

In the second ≈ 49 it loads the available hours

The .env file looks like this: 
```
POSTGRES_USER=unicorn_user
POSTGRES_PASSWORD=magical_password
POSTGRES_DB=calendso
DATABASE_URL='postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}'
GOOGLE_API_CREDENTIALS='AyDS0C-OioHC-cUr27Qpid46VHE'
BASE_URL='http://agendar.incubadoradeases.com:3000'
NEXTAUTH_URL='http://agendar.incubadoradeases.com:3000'

# Remove this var if you don't want Calendso to collect anonymous usage
NEXT_PUBLIC_TELEMETRY_KEY=js.2pvs2bbpqq1zwcml.oi2jzirnbj1ev4tc57c5r

# Used for the Office 365 / Outlook.com Calendar integration
MS_GRAPH_CLIENT_ID=
MS_GRAPH_CLIENT_SECRET=

# Used for the Zoom integration
ZOOM_CLIENT_ID=I7TT8dRac9g
ZOOM_CLIENT_SECRET=c207KEwTtSIhP9gY

# E-mail settings
# Configures the global From: header whilst sending emails.
EMAIL_FROM='info@incubadoradeases.cl'

# Configure SMTP settings (@see https://nodemailer.com/smtp/).
EMAIL_SERVER_HOST='smtp.example.com'
EMAIL_SERVER_PORT=587
EMAIL_SERVER_USER='email_user'
EMAIL_SERVER_PASSWORD='email_password'                                                                                     
```

**Comment by emrysal** [comment]
Hey @ipozow - I (very) recently put in some changes to the Dockerfile to tackle this issue; could you check if the issue persist with the latest changes?

**Comment by ipozow** [comment]
I am having a really hard time with the `docker-compose exec calendso -- npx prisma studio` command. Tried with `docker-compose exec calendso npx prisma studio` but isn't working now. Calendso is working but I can't launch prisma to create a user, and I lost that data because I ended up reinstalling the server
I am sorry for the late reply

**Comment by ipozow** [comment]
It's working good now, thanks a lot. 
If anyone as the prisma problem I just rebooted and it worked
